# Generated by Django 3.2 on 2023-04-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.candidate'),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.jobdetails'),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='max_salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='min_salary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='resume',
            field=models.FileField(null=True, upload_to='app/resume'),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='joblocation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobregion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='postalcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='app/candidate/img'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(null=True, upload_to='app/candidate/resume'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.usermaster'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(null=True, upload_to='app/img/company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.usermaster'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyaddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companycontact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyemail',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companywebsite',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobtype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', null=True, upload_to='app/img/jobpost'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='qualification',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibilties',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='salarypackage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
